vich_uploader:
    db_driver: orm

    mappings:
       post_image:
           uri_prefix: /image/post_image
           upload_destination: '%kernel.project_dir%/public/image/post_image'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer


       user_image:
           uri_prefix: /image/user_image
           upload_destination: '%kernel.project_dir%/public/image/user_image'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

  

